### ISSUE TITLE
Computing entropy

### ISSUE THREAD

**Issue by KateKraft** [KwatME/ccal#15]
You use this function in model and infer to filter out features or samples that have enrichment in too many NMF factors. 

I'm wondering, in the function, why do you multiply the log(probability) by probability? Why dont you just take the sum of the -log(probability)? Are you just trying to make the numbers smaller? Even if the numbers are larger you're just taking the top X percent. For me, the less steps that happen in the back, the easier the results are to understand.

![screen shot 2019-01-22 at 11 20 32 am](https://user-images.githubusercontent.com/20215501/51559881-f725e080-1e37-11e9-8ec2-18b0275c96cc.png)

**Comment by pablotamayo** [comment]
Hi Kate,

  The reason is because the entropy is the "mean" of the information (-log
p). The sum (or integral) needs to include the probability p of each
information term (-log p) in order to compute the mean or expected value.

 The mean of any function of a probability F(p) will be computed the same
way:

mean(F) = sum p * F(p)

This video may give you a more intuitive idea:

https://www.khanacademy.org/computing/computer-science/informationtheory/moderninfotheory/v/information-entropy

--Pablo
___________________________________________________________
Dr. Pablo Tamayo (ptamayo@ucsd.edu)

Director, *UCSD Center for Cancer Target Discovery and Development (CTD2)*
Group Leader, *Computational Cancer Analysis Laboratory (CCAL)*
Co-Director, *Genomics and Computational Biology Shared Resource (GCBSR)*
Professor, *Division of Medical Genetics, UC San Diego School of Medicine*
Visiting Scientist, *Cancer Program, Broad Institute of MIT/Harvard*

*UC San Diego Moores Cancer Center (*Room 3017)
3855 Health Sciences Drive MC 0658, La Jolla, CA  92093-0658
___________________________________________________________

**Comment by KateKraft** [comment]
Thanks Pablo.
